/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2025-10-14 10:05:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import com.database.DatabaseImplementation;

public final class Register1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"sytlesheet\" href=\"./css/mystyle.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("h1 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body\r\n");
      out.write("\tstyle=\"background-image: url('pexels-simon-berger-1323550.jpg'); background-repeat: no-repeat;background-attachment: fixed;\r\n");
      out.write("  background-size: cover;\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-light bg-info\"> <a\r\n");
      out.write("\t\t\tclass=\"navbar-brand\" href=\"#\"></a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-target=\"#navbarNavAltMarkup\" aria-controls=\"navbarNavAltMarkup\"\r\n");
      out.write("\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarNavAltMarkup\">\r\n");
      out.write("\t\t\t<div class=\"navbar-nav\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<h3 style=\"padding: 30px;\">\r\n");
      out.write("PUBLICLY SHARED A DYNAMIC DATA WITH PRIVACY PRESERVING IN CLOUD\r\n");
      out.write("</h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<h1 style>REGISTER</h1>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\" style=\"border-style: solid;\">\r\n");
      out.write("\t\t\t<div class=\"col-3\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"register\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<label class=\"myfont\" style=\"margin-bottom: 10px;\">Enter\r\n");
      out.write("\t\t\t\t\t\tName</label><br /> <input type=\"text\" name=\"name1\" /><br /> <label\r\n");
      out.write("\t\t\t\t\t\tclass=\"myfont\" style=\"margin-bottom: 10px;\">Enter DOB </label><br />\r\n");
      out.write("\t\t\t\t\t<input type=\"date\" name=\"date\" /><br /> <label class=\"myfont\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-bottom: 10px;\">Enter Email</label><br /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"email\" name=\"email\" /><br /> <label class=\"myfont\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-bottom: 10px;\">Enter Password</label><br /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" name=\"password\" /><br /> <label>Select\r\n");
      out.write("\t\t\t\t\t\tGender</label><br /> <input type=\"radio\" name=\"gender\" value=\"male\">\r\n");
      out.write("\t\t\t\t\tMale<br> <input type=\"radio\" name=\"gender\" value=\"female\">\r\n");
      out.write("\t\t\t\t\tFemale<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm\">\r\n");
      out.write("\t\t\t\t<h1></h1>\r\n");
      out.write("\t\t\t\t<label class=\"myfont\" style=\"margin-bottom: 10px;\">Enter\r\n");
      out.write("\t\t\t\t\tPhone Number</label><br /> <input type=\"text\" name=\"pnumber\" /><br /> <label\r\n");
      out.write("\t\t\t\t\tclass=\"myfont\" style=\"margin-bottom: 10px;\">Enter Adress</label><br />\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"adress\" /><br /> <label for=\"cars\">Choose Groups :</label> <select name=\"group\">\r\n");
      out.write("\t\t\t\t\t");

DatabaseImplementation di=new DatabaseImplementation();
List<String> al=di.groups();
for(String s: al){
      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=");
      out.print(s );
      out.write('>');
      out.print(s );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");
}

      out.write("\r\n");
      out.write("\t\t\t\t</select> <input type=\"submit\" \" value=\"Register\" style=\"margin-top: 10px;\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-success\" /><br />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
